# Generated by Django 5.1.3 on 2024-12-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_docs', '0001_initial'),
        ('topics', '0003_alter_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoc',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='topics.topic'),
        ),
    ]
