# Generated by Django 5.1.3 on 2025-01-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_docs', '0002_adddoc_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddoc',
            name='file',
        ),
        migrations.AddField(
            model_name='adddoc',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
